export const GridSampleOrder: Object = [
  {
    'path': 'grid/overview', 'component': 'OverView', 'name': 'Overview', 'description': 'This demo for Essential JS 2 grid component is an overview of how to display and manipulate large data with configuration options.', 'order': '01', 'category': 'Data Grid', 'api': '{"GridComponent":["queryCellInfo","dataSource","enableVirtualization","allowFiltering","allowSorting","allowSelection","selectionSettings","height","columns","dataBound","actionComplete","load"] }',
    'sourceFiles': [{ 'displayName': 'overview.tsx', 'path': '/nextjs/demos/src/grid/overview/page.tsx' }, { 'displayName': 'overview.css', 'path': '/nextjs/demos/src/grid/overview/grid-overview.css' }]
  },
  {
    'path': 'grid/live-data', 'component': 'LiveStream', 'name': 'Live Data', 'order': '01', 'description': 'This demo for Essential JS 2 grid component shows how frequently the Grid cell is updated with real-time data.', 'category': 'Data Grid', 'api': '{"GridComponent":["dataSource","enableVirtualization","enableVirtualMaskRow","enableHover", "columns", "rowHeight", "height", "allowSelection", "queryCellInfo", "load"]}',
    'sourceFiles': [{ 'displayName': 'live-data.tsx', 'path': '/nextjs/demos/src/grid/live-data/page.tsx' }, { 'displayName': 'live-data.css', 'path': '/nextjs/demos/src/grid/live-data/live-data.css' }]
  },
  { 'path': 'grid/default', 'component': 'Default', 'name': 'Default Functionalities', 'order': '01', 'description':'This demo for Essential JS 2 grid component shows the default rendering of the grid component with minimum configuration.', 'category': 'Data Grid' ,'api':'{"GridComponent":["columns","dataSource"] }'},
  { 'path': 'grid/adaptive-layout', 'component': 'AdaptiveLayout', 'name': 'Adaptive Layout', 'order': '01', 'description': 'This demo for Essential JS 2 grid component shows the Grid row in vertical direction and helps to show the grid dialogs in full screen.', 'category': 'Data Grid', 'api': '{"GridComponent":["dataSource","allowSorting","allowPaging", "columns", "editSettings", "allowFiltering", "filterSettings", "rowRenderingMode", "toolbar", "Aggregate"]}' },
  { 'path': 'grid/loading-animation', 'component': 'LoadingAnimation', 'name': 'Loading Animation', 'order': '01', 'description':'This demo for Essential JS 2 grid component shows the loading indicator when grid loading and refreshing.', 'category': 'Data Grid', 'api':'{"GridComponent":["columns", "dataSource","allowSorting","allowPaging", "allowFiltering", "loadingIndicator", "pageSettings"]}' },
  { 'path': 'grid/empty-record-template', 'component': 'EmptyRecordTemplate', 'name': 'Empty Record Template', 'order': '01', 'description':'This demo for Essential JS 2 grid component demonstrates usage of the empty record template in the DataGrid', 'category': 'Data Grid', 'api':'{"GridComponent":["columns", "dataSource", "editSettings", "toolbar", "allowPaging", "pageSettings"]}' },
  
  { 'path': 'grid/local-binding', 'component': 'Localbinding', 'name': 'Local Data', 'order': '02', 'description':'This demo for Essential JS 2 grid control demonstrates the way for binding a grid with a local data source.', 'category': 'Data Binding','api':'{"GridComponent":["dataSource","allowPaging","columns","pageSettings"] }' },
  { 'path': 'grid/remote-data', 'component': 'RemoteDataBinding', 'name': 'Remote Data', 'order': '02', 'description':'This demo for Essential JS 2 grid control shows the way of data binding grid with remote service. Grid data source is bound to remote data using DataManager.', 'category': 'Data Binding','api':'{"GridComponent":["dataSource","allowPaging","columns","pageSettings"] }' },
  { 'path': 'grid/custom-binding', 'component': 'CustomBinding', 'name': 'Custom Binding', 'order': '02', 'description': 'This demo for Essential JS 2 grid component shows how to bind the data using custom data binding. It shows the way of binding data to the grid.', 'category': 'Data Binding', 'api': '{"GridComponent":["dataSource","allowPaging","columns","pageSettings","allowSorting", "allowGrouping"] }' },

  { 'path': 'grid/column-template', 'component': 'ColumnTemplate', 'name': 'Column Template', 'order': '03', 'description': 'This demo for Essential JS 2 grid control demonstrates usage of template columns in Grid to shown custom images in the Employee Image column.', 'category': 'Columns', 'api': '{"GridComponent":["dataSource","columns","width","height"] }' },
  { 'path': 'grid/stacked-header', 'component': 'StackedHeader', 'name': 'Stacked Header', 'description':'This demo for Essential JS 2 grid control shows the usage of the sorting API in grid. Use the properties panel to sort/unsort columns using API.', 'order': '03', 'category': 'Columns','api':'{"GridComponent":["dataSource","allowPaging","pageSettings","columns", "allowResizing", "allowSorting"] }'},
  { 'path': 'grid/foreign-key', 'component': 'ForeignKeyColumn', 'name': 'Foreign Key Column', 'description':'This demo for Essential JS 2 grid control shows the usage of a foreign key column and perform actions like filtering, sorting and editing.', 'order': '03', 'category': 'Columns', 'api':'{"GridComponent":["dataSource","allowSorting","allowPaging", "columns", "allowFiltering", "filterSettings", "editSettings"]}'},
  { 'path': 'grid/reorder', 'component': 'Reordering', 'name': 'Reorder', 'order': '03', 'description':'This demo for Essential JS 2 grid control shows the reordering columns feature. Select column name and index from properties panel to reorder the columns.', 'category': 'Columns','api':'{"GridComponent":["dataSource","allowReordering","actionComplete","columns"] }' },


  { 'path': 'grid/batch', 'component': 'BatchEdit', 'name': 'Batch Editing', 'order': '05', 'description':'This demo for Essential JS 2 grid component shows how to perform bulk changes to the grid content using batch edit mode.', 'category': 'Editing','api':'{"GridComponent":["dataSource","allowPaging","pageSettings","columns","editSettings","toolbar"] }'},
  { 'path': 'grid/filter-menu', 'component': 'FilterMenu', 'name': 'Filter Menu', 'order': '06', 'category': 'Filtering', 'description':'This demo for Essential JS 2 grid component demonstrates a way of filtering rows using a menu, check box, and Excel filter UI.', 'api':'{"GridComponent":["allowFiltering","filterSettings","dataSource","allowPaging","pageSettings","columns"] }' },
  { 'path': 'grid/reactive-aggregate', 'component': 'ReactiveAggregate', 'name': 'Reactive Aggregate', 'order': '07', 'description': 'This demo for Essential JS 2 grid component shows how the row values can be updated while the data is modified.', 'category': 'Aggregates','api':'{"GridComponent":["dataSource","allowPaging","pageSettings","columns","Aggregate", "Group", "Edit","Toolbar"] }'},

  { 'path': 'grid/lazy-load-grouping-with-paging', 'component': 'LazyLoadGrouping', 'name': 'Grouping with Paging', 'type': 'update', 'order': '14', 'description':'This demo for Essential JS 2 grid control shows demonstrates the usage of the lazy load grouping feature.', 'category': 'Lazy Load Grouping','api':'{"GridComponent":["dataSource","allowPaging","groupSettings","allowGrouping","height","columns"] }' },
  { 'path': 'grid/lazy-load-grouping-with-infinite-scrolling', 'component': 'LazyLoadGroupingWithInfiniteScrolling', 'name': 'Grouping with Infinite Scrolling', 'type': 'update', 'order': '14', 'description':'This demo for Essential JS 2 grid control shows demonstrates the usage of the lazy load grouping feature with infinite scrolling.', 'category': 'Lazy Load Grouping','api':'{"GridComponent":["dataSource","enableInfiniteScrolling","height","allowGrouping","groupSettings","columns"] }' },
  { 'path': 'grid/lazy-load-grouping-with-virtual-scrolling', 'component': 'LazyLoadGroupingWithVirtualScrolling', 'name': 'Grouping with Virtual Scrolling', 'type': 'update', 'order': '14', 'description':'This demo for Essential JS 2 grid control shows demonstrates the usage of the lazy load grouping feature with virtual scrolling.', 'category': 'Lazy Load Grouping','api':'{"GridComponent":["dataSource","enableVirtualization","height","allowGrouping","groupSettings","columns"] }' },

  { 'path': 'grid/advanced-exporting', 'component': 'AdvancedExporting', 'name': 'Advanced Exporting', 'order': '08', 'description':'This demo for Essential JS 2 grid component demonstrates how exporting can be customized to add headers and footers in exported documents.', 'category': 'Exporting','api':'{"GridComponent":["dataSource","allowExcelExport","allowPdfExport","toolbar","allowPaging","pageSettings","columns"] }'},
  { 'path': 'grid/keyboard-navigation', 'component': 'KeyboardNavigation', 'name': 'Keyboard Navigation', 'order': '09', 'description':'This demo for Essential JS 2 grid component shows the keyboard navigation in grid which shows the different key function.', 'category': 'Miscellaneous', 'api':'{"GridComponent":["dataSource", "allowFiltering", "columns", "allowGrouping", "allowPaging", "allowSorting", "toolbar", "filterSettings", "pageSettings", "editSettings"]}'}
]
