export const DropDownTreeSampleOrder: Object = [
    { 'path': 'drop-down-tree/default', 'component': 'Default', 'name': 'Default Functionalities', 'description': 'This example demonstrates the default functionalities of the React drop-down tree component with minimum configuration.', 'order': '01', 'category': 'Dropdown Tree', 'api': '{"DropDownTree": ["popupHeight", "placeholder", "change", "fields"]}', 'sourceFiles': [{ 'displayName': 'default.tsx', 'path': '/nextjs/demos/src/drop-down-tree/default/page.tsx' }, { 'displayName': 'default-data.json', 'path': '/nextjs/demos/src/drop-down-tree/default/default-data.json' }] },
    { 'path': 'drop-down-tree/icons', 'component': 'Icons', 'name': 'Icons and Images', 'description': 'The Dropdown Tree items can be rendered with any custom icons. This sample demonstrated like a file system with custom icons and images.', 'order': '01', 'category': 'Dropdown Tree', 'api': '{"DropDownTree": ["popupHeight", "placeholder", "fields"]}', 'sourceFiles': [{ 'displayName': 'icons.tsx', 'path': '/nextjs/demos/src/drop-down-tree/icons/page.tsx' }, { 'displayName': 'icons-data.json', 'path': '/nextjs/demos/src/drop-down-tree/icons/icons-data.json' }] },
    { 'path': 'drop-down-tree/checkbox', 'component': 'Checkbox', 'name': 'Checkbox', 'description': 'This demo demonstrates the Dropdown Tree with checkbox functionality, this allows the user to check more than one items.', 'order': '01', 'category': 'Dropdown Tree', 'api': '{"DropDownTree": ["popupHeight", "placeholder", "fields"]}', 'sourceFiles': [{ 'displayName': 'checkbox.tsx', 'path': '/nextjs/demos/src/drop-down-tree/checkbox/page.tsx' }, { 'displayName': 'checkbox-data.json', 'path': '/nextjs/demos/src/drop-down-tree/checkbox/checkbox-data.json' }] },
    { 'path': 'drop-down-tree/multiple-selection', 'component': 'MultiSelect', 'name': 'Multiple Selection', 'description': 'The Dropdown Tree component allows to select multiple items by pressing CTRL key, also can select the range of items by pressing SHIFT key.', 'order': '01', 'category': 'Dropdown Tree', 'api': '{"DropDownTree": ["popupHeight", "placeholder", "fields"]}', 'sourceFiles': [{ 'displayName': 'multiple-selection.tsx', 'path': '/nextjs/demos/src/drop-down-tree/multiple-selection/page.tsx' }, { 'displayName': 'multiSelect-data.json', 'path': '/nextjs/demos/src/drop-down-tree/multiple-selection/multiSelect-data.json' }] },
    { 'path': 'drop-down-tree/template', 'component': 'Templates', 'name': 'Template', 'description': 'This example demonstrates how to customize the appearance of each item in the React Dropdown Tree component pop-up list using the template.', 'order': '01', 'category': 'Dropdown Tree', 'api': '{"DropDownTree": ["popupHeight", "placeholder", "fields", "headerTemplate", "itemTemplate", "footerTemplate"]}', 'sourceFiles': [{ 'displayName': 'template.tsx', 'path': '/nextjs/demos/src/drop-down-tree/template/page.tsx' }, { 'displayName': 'template-data.json', 'path': '/nextjs/demos/src/drop-down-tree/template/template-data.json' }] },
    { 'path': 'drop-down-tree/custom-template', 'component': 'CustomTemplate', 'name': 'Custom Template', 'description': 'This example demonstrates how to customize the display text of the selected items in the React drop-down tree component using the customTemplate.', 'order': '01', 'category': 'Dropdown Tree', 'api': '{"DropDownTree": ["popupHeight", "placeholder", "fields", "mode", "customTemplate"]}', 'sourceFiles': [{ 'displayName': 'custom-template.tsx', 'path': '/nextjs/demos/src/drop-down-tree/custom-template/page.tsx' }, { 'displayName': 'customTemplate-data.json', 'path': '/nextjs/demos/src/drop-down-tree/custom-template/customTemplate-data.json' }] },
    { 'path': 'drop-down-tree/filtering', 'component': 'Filtering', 'name': 'Filtering', 'description': 'This example for React drop-down tree component explains the choosing an item from the filtered list based on the typed characters.', 'order': '01', 'category': 'Dropdown Tree', 'api': '{"DropDownTree": ["popupHeight", "allowFiltering", "filterBarPlaceholder", "placeholder", "fields"]}', 'sourceFiles': [{ 'displayName': 'filtering.tsx', 'path': '/nextjs/demos/src/drop-down-tree/filtering/page.tsx' }, { 'displayName': 'filtering-data.json', 'path': '/nextjs/demos/src/drop-down-tree/filtering/filtering-data.json' }] },
    { 'path': 'drop-down-tree/local-data', 'component': 'LocalData', 'name': 'Local Data', 'description': 'This demo demonstrates the binding of local data to the React drop-down tree component. The local data structure can be hierarchical data or list data.', 'order': '02', 'category': 'Data Binding', 'api': '{"DropDownTree": ["fields", "popupHeight", "placeholder"]}', 'sourceFiles': [{ 'displayName': 'local-data.tsx', 'path': '/nextjs/demos/src/drop-down-tree/local-data/page.tsx' }, { 'displayName': 'local-data.json', 'path': '/nextjs/demos/src/drop-down-tree/local-data/local-data.json' }] },
    { 'path': 'drop-down-tree/remote-data', 'component': 'RemoteData', 'name': 'Remote Data', 'description': 'This example demonstrates how to fetch data from remote data service in the React drop-down tree component.', 'order': '02', 'category': 'Data Binding', 'api': '{"DropDownTree": ["fields", "popupHeight", "placeholder"]}', 'sourceFiles': [{ 'displayName': 'remote-data.tsx', 'path': '/nextjs/demos/src/drop-down-tree/remote-data/page.tsx' }] }
]