export const AvatarSampleOrder: Object = [
    { 'path': 'avatar/default', 'component': 'Default', 'name': 'Default', 'description': 'Demo of the pure CSS Essential JS 2 Avatar component displaying profile images in different sizes in both default and circle shapes.', 'order': '01', 'category': 'Avatar', 'sourceFiles': [
        { 'displayName': 'default.tsx', 'path': '/nextjs/demos/src/avatar/default/page.tsx' },{ 'displayName': 'default.css', 'path': '/nextjs/demos/src/avatar/default/default.css' }] },
    { 'path': 'avatar/types', 'component': 'Types', 'name': 'Types', 'description': 'Demo of the pure CSS Essential JS 2 Avatar components supported media formats for avatar content: images, SVG, initials, font icons, and words.', 'order': '01', 'category': 'Avatar', 'sourceFiles': [
        { 'displayName': 'types.tsx', 'path': '/nextjs/demos/src/avatar/types/page.tsx' },{ 'displayName': 'types.css', 'path': '/nextjs/demos/src/avatar/types/types.css' }] },
    { 'path': 'avatar/badge', 'component': 'Badge', 'name': 'Badge', 'description': 'Demo integrating the Essential JS 2 Avatar and Badge components to display a notification count on profile images, similar to Gmail.','order': '02', 'category': 'Integration', 'sourceFiles': [
        { 'displayName': 'badge.tsx', 'path': '/nextjs/demos/src/avatar/badge/page.tsx' },{ 'displayName': 'badge.css', 'path': '/nextjs/demos/src/avatar/badge/badge.css' }] },
    { 'path': 'avatar/listview', 'component': 'Listview', 'name': 'ListView', 'description': 'Demo integrating the Essential JS 2 Avatar and ListView components to display profile images or letters in a mobile contact application.', 'order': '02', 'category': 'Integration', 'sourceFiles': [
        { 'displayName': 'listview.tsx', 'path': '/nextjs/demos/src/avatar/listview/page.tsx' },{ 'displayName': 'listview.css', 'path': '/nextjs/demos/src/avatar/listview/listview.css' },{ 'displayName': 'datasource.ts', 'path': '/nextjs/demos/src/avatar/listview/datasource.ts' }] },
    { 'path': 'avatar/card', 'component': 'Card', 'name': 'Card', 'description': 'Demo integrating the Essential JS 2 Avatar and Card components to display business cards for employees with profile images, roles, and responsibilities.', 'order': '02', 'category': 'Integration', 'sourceFiles': [
        { 'displayName': 'card.tsx', 'path': '/nextjs/demos/src/avatar/card/page.tsx' },{ 'displayName': 'card.css', 'path': '/nextjs/demos/src/avatar/card/card.css' }] }
]